"""Type stubs for pyqpanda3.core."""

from typing import Any

class QProg:
    """Квантовая программа — контейнер гейтов."""

    def __lshift__(self, gate: Any) -> QProg: ...

class CPUQVM:
    """Локальный квантовый симулятор."""

    def run(self, prog: QProg, shots: int = 1000) -> None: ...
    def result(self) -> Any: ...

class Job:
    """Квантовое задание."""

    def result(self) -> Any: ...
    def status(self) -> str: ...
    def job_id(self) -> str: ...

class Backend:
    """Квантовый бэкенд."""

    def run(
        self,
        prog: QProg,
        shots: int = 1000,
        options: Any | None = None,
    ) -> Job: ...

def H(qubit: int) -> Any: ...
def X(qubit: int) -> Any: ...
def Z(qubit: int) -> Any: ...
def RX(qubit: int, theta: float) -> Any: ...
def RY(qubit: int, theta: float) -> Any: ...
def RZ(qubit: int, theta: float) -> Any: ...
def CNOT(control: int, target: int) -> Any: ...
def measure(qubits: list[int], cbits: list[int]) -> Any: ...
