"""Type stubs for pyqpanda3.qcloud."""

from typing import Any

class QCloudOptions:
    """Опции для облачного запуска."""

    def set_amend(self, value: bool) -> None: ...
    def set_mapping(self, value: bool) -> None: ...
    def set_optimization(self, value: bool) -> None: ...
    def set_is_prob_counts(self, value: bool) -> None: ...
    def set_specified_block(self, qubits: list[int]) -> None: ...

class QCloudService:
    """Сервис облачной платформы OriginQ."""

    def __init__(self, api_key: str) -> None: ...
    def backend(self, chip_name: str) -> QCloudBackend: ...

class QCloudBackend:
    """Облачный квантовый бэкенд."""

    def run(
        self,
        prog: Any,
        shots: int = 1000,
        options: QCloudOptions | None = None,
    ) -> QCloudJob: ...
    def chip_backend(self) -> Any: ...

class QCloudJob:
    """Облачное задание."""

    def result(self) -> Any: ...
    def status(self) -> str: ...
    def job_id(self) -> str: ...
